version: '3'
services:
  web:
    build: .
    ports:
      - '3009:3000'
    links:
      - postgres
      - mongo
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - MONGODB_URI=mongodb://mongo/express-museum
  postgres:
    image: postgres:10
  mongo:
    image: mongo:latest
